import React, { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import { STORAGE_KEYS, storage } from '../utils/storage';

interface Translations {
  [key: string]: string;
}

const translations: { [lang: string]: Translations } = {
  en: {
    // Home
    todaySales: "Today's Sales",
    todayProfit: "Today's Profit",
    totalProducts: 'Total Products',
    totalCustomers: 'Total Customers',
    alerts: 'Alerts',
    lowStock: 'Low Stock Alert',
    itemsLowStock: 'items are low in stock',
    pendingLoans: 'Pending Loans',
    inPendingLoans: 'in pending loans',
    quickActions: 'Quick Actions',
    newSale: 'New Sale',
    addProduct: 'Add Product',
    addCustomer: 'Add Customer',
    viewReports: 'View Reports',
    refresh: 'Refresh',
    logout: 'Log Out',
    months: 'months',
    warrantyExpires: 'Warranty until',
    expiredWarranties: 'Expired warranties',
    expiredWarrantiesHint: 'past warranty — safe to archive',
    archiveReceipt: 'Archive',
    restoreReceipt: 'Restore',
    showArchived: 'Show archived',
    showActive: 'Show active',
    contactType: 'Type',
    winga: 'Winga',
    walkInCustomer: 'Customer',
    noWarranty: 'No warranty',

    // Products
    products: 'Products',
    searchProducts: 'Search products...',
    noProducts: 'No Products Found',
    addFirstProduct: 'Add your first product to get started',
    editProduct: 'Edit Product',
    productName: 'Product Name',
    enterProductName: 'Enter product name',
    brand: 'Brand',
    enterBrand: 'Enter brand',
    category: 'Category',
    enterCategory: 'Enter category',
    buyingPrice: 'Buying Price',
    sellingPrice: 'Selling Price',
    pieces: 'Pieces',
    lowStockAlert: 'Low Stock Alert',
    calculations: 'Calculations',
    profitPerUnit: 'Profit per Unit',
    profitMargin: 'Profit Margin',
    totalCost: 'Total Cost',
    profit: 'Profit',
    totalValue: 'Total Value',
    lowStockWarning: 'Low stock warning',
    threshold: 'Threshold',

    // Sales
    pointOfSale: 'Point of Sale',
    cart: 'Cart',
    addToCart: 'Add to Cart',
    removeFromCart: 'Remove from Cart',
    clearCart: 'Clear Cart',
    checkout: 'Checkout',
    total: 'Total',
    subtotal: 'Subtotal',
    cash: 'Cash',
    change: 'Change',
    completeSale: 'Complete Sale',

    // Customers
    customers: 'Customers',
    searchCustomers: 'Search customers...',
    noCustomers: 'No Customers Found',
    addFirstCustomer: 'Add your first customer to get started',
    editCustomer: 'Edit Customer',
    customerName: 'Customer Name',
    enterCustomerName: 'Enter customer name',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter phone number',
    email: 'Email',
    enterEmail: 'Enter email address',
    address: 'Address',
    enterAddress: 'Enter address',
    loyaltyPoints: 'Loyalty Points',
    loanBalance: 'Loan Balance',
    payLoan: 'Pay Loan',
    addLoan: 'Add Loan',
    loanHistory: 'Loan History',

    // Reports
    reports: 'Reports & Analytics',
    financialSummary: 'Financial Summary',
    lossInformation: 'Loss Information',
    currentLoss: 'Current loss',
    currentProfit: 'Current profit',
    revenue: 'Revenue',
    cost: 'Cost',
    keyMetrics: 'Key Metrics',
    totalSales: 'Total Sales',
    inventoryValue: 'Inventory Value',
    activeCustomers: 'Active Customers',
    pendingLoansReport: 'Pending Loans',
    lowStockAlertReport: 'Low Stock Alert',
    productPerformance: 'Product Performance',
    customerInsights: 'Customer Insights',
    totalLoyaltyPoints: 'Total Loyalty Points',
    customersWithLoans: 'Customers with Loans',
    averageLoan: 'Average Loan',
    today: 'Today',
    week: 'Week',
    month: 'Month',
    remaining: 'remaining',
    units: 'units',
    items: 'items',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    confirmDelete: 'Confirm Delete',
    confirmDeleteProduct: 'Are you sure you want to delete this product?',
    confirmDeleteCustomer: 'Are you sure you want to delete this customer?',
    fillAllFields: 'Please fill all required fields',
    ok: 'OK',
    home: 'Home', pos: 'POS', receipts: 'Receipts', workspace: 'Business workspace',
    price: 'Price', stock: 'Stock', actions: 'Actions', totalLoans: 'Total Loans', totalPoints: 'Total Points',
    selectCustomer: 'Select Customer', newProduct: 'New product', saveAndAdd: 'Save & add',
    orderSummary: 'Order Summary', payment: 'Payment', customerNameOptional: 'Customer name (optional)',
    enterCustomerReceipt: 'Enter customer name for the receipt', selectCustomerTitle: 'Select Customer',
    done: 'Done', applyDiscount: 'Apply Discount', apply: 'Apply', discountPercentage: 'Discount Percentage (%)',
    saleReceipt: 'Sale Receipt', receiptDetails: 'Receipt Details', receiptsHistory: 'Receipts history',
    searchReceipts: 'Search receipts by ID, date, or amount...', noReceipts: 'No receipts found',
    adjustSearch: 'Try adjusting your search', receiptsAfterSales: 'Receipts will appear here after sales',
    customerInformation: 'Customer Information', cashSaleNoCustomer: 'No Customer (Cash Sale)',
    itemsPurchased: 'Items Purchased', cashReceived: 'Cash Received',
    signature: 'Signature', notes: 'Description/Notes', enterSignature: 'Enter signature',
    enterNotes: 'Add any notes or description', productOutOfStock: 'Product out of stock',
    notEnoughStock: 'Not enough stock available', cartEmpty: 'Cart is empty', insufficientCash: 'Insufficient cash received',
    loan: 'Loan', loanManagement: 'Loan Management', addLoanAmount: 'Add Loan Amount', paymentAmount: 'Payment Amount',
    newBalanceCalculation: 'New Balance Calculation', createAccount: 'Create Account', welcomeBack: 'Welcome Back',
    signIn: 'Sign In', signUp: 'Sign Up', password: 'Password', confirmPassword: 'Confirm Password',
    fullName: 'Full Name', shopName: 'Shop Name', username: 'Username', phone: 'Phone',
    resetPassword: 'Reset Password', updatePassword: 'Update password',
    expenses: 'Expenses', monthlyExpenses: 'This month', addExpense: 'Add Expense', amount: 'Amount',
    description: 'Description', noDescription: 'No description', noExpenses: 'No expenses recorded',
    validExpense: 'Enter a category and an amount greater than zero', expenseSaveFailed: 'Expense could not be saved',
    netProfit: 'Net Profit', operatingExpenses: 'Operating Expenses', inventoryMovements: 'Inventory Movements',
    more: 'More', inventory: 'Inventory', businessTools: 'Business tools and records',
    customerManagement: 'Customer accounts, loyalty and loans', expenseManagement: 'Record and review operating costs',
    shareReceipt: 'Share / PDF',
    allowPopups: 'Allow pop-ups for this site to open the printable receipt',

    // Payment methods. Mobile money is how most Tanzanian counters get paid.
    paymentMethod: 'Payment Method',
    cashPayment: 'Cash',
    mpesa: 'M-Pesa',
    tigopesa: 'Mixx by Yas',
    airtelmoney: 'Airtel Money',
    halopesa: 'HaloPesa',
    azampesa: 'Azam Pesa',
    bankTransfer: 'Bank Transfer',
    splitPayment: 'Split Payment',
    reference: 'Reference',
    transactionRef: 'Transaction reference',
    enterReference: 'Enter mobile money reference',

    // Serialised stock
    serialNumbers: 'IMEI / Serial Numbers',
    addImei: 'Add IMEI',
    imeiList: 'Registered IMEIs',
    searchByImei: 'Search by IMEI, name or brand',
    imeiNotFound: 'No item matches that IMEI',
    imeiAlreadyExists: 'That IMEI is already registered',
    imeiInvalid: 'An IMEI must be 15 digits',
    selectUnit: 'Select unit',
    unitStatus: 'Status',
    unitInStock: 'In stock',
    unitSold: 'Sold',
    unitReturned: 'Returned',
    unitFaulty: 'Faulty',
    unitsRequired: 'Register one IMEI for each phone in stock',
    imeiLookup: 'IMEI Lookup',
    soldOn: 'Sold on',
    soldTo: 'Sold to',
    warranty: 'Warranty',
    warrantyValid: 'Under warranty',
    warrantyExpired: 'Warranty expired',

    // Losses and returns
    recordLoss: 'Record Loss',
    lossReason: 'Reason',
    damaged: 'Damaged',
    stolen: 'Stolen',
    defective: 'Defective',
    lostItem: 'Lost',
    returnSale: 'Return / Refund',
    processReturn: 'Process Return',
    returnReason: 'Return reason',
    refundAmount: 'Refund amount',
    returnRecorded: 'Return recorded and stock restored',

    // Appearance and system
    appearance: 'Appearance',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    settings: 'Settings',
    language: 'Language',
    offline: 'Offline',
    online: 'Online',
    offlineNotice: 'You are offline. Sales are saved on this device and will sync automatically.',
    pendingSync: 'waiting to sync',
    syncNow: 'Sync now',
    syncing: 'Syncing',
    synced: 'All changes synced',
    retry: 'Retry',
    close: 'Close',
    all: 'All',
    clear: 'Clear',

    // Signup / auth errors
    usernameTaken: 'That username is already taken. Choose another.',
    usernameChecking: 'Checking availability…',
    usernameAvailable: 'Username is available',
    emailRateLimited: 'Too many verification emails have been sent. Please wait about an hour and try again.',
    emailNotConfirmed: 'Your email is not verified yet. Check your inbox, or resend the verification email below.',
    invalidCredentials: 'Incorrect email or password. Use the email address you signed up with.',
    signupSuccess: 'Account created. Check your email to verify your account before signing in.',
    verificationSent: 'Verification email sent. Check your inbox and spam folder.',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    enterEmailFirst: 'Enter your email address first.',
    unexpectedError: 'Something went wrong. Please try again.',
    passwordUpdated: 'Your password has been updated.',
    resetLinkExpired: 'This reset link has expired or was already used. Request a new one.',

    // Previously missing: these rendered as their raw key on screen
    // (the category buttons literally read "accessories" and "phones").
    accessories: 'Accessories',
    reportsShort: 'Reports',
    phones: 'Phones',
    enterIMEI: 'Enter 15-digit IMEI',
    product: 'Product',
    quantity: 'Quantity',
    loss: 'Loss',
    piecesSold: 'sold',
    discountSummary: 'Discounts',
    totalDiscountsGiven: 'Total Discounts Given',
    averageDiscount: 'Average Discount',
  },
  sw: {
    // Home
    todaySales: 'Mauzo ya Leo',
    todayProfit: 'Faida ya Leo',
    totalProducts: 'Bidhaa Zote',
    totalCustomers: 'Wateja Wote',
    alerts: 'Arifa',
    lowStock: 'Arifa ya Stock Kidogo',
    itemsLowStock: 'bidhaa zina stock kidogo',
    pendingLoans: 'Mikopo Inayosubiri',
    inPendingLoans: 'katika mikopo inayosubiri',
    quickActions: 'Vitendo vya Haraka',
    newSale: 'Mauzo Mapya',
    addProduct: 'Ongeza Bidhaa',
    addCustomer: 'Ongeza Mteja',
    viewReports: 'Ona Ripoti',
    refresh: 'Sasisha',
    logout: 'Ondoka',
    months: 'miezi',
    warrantyExpires: 'Dhamana hadi',
    expiredWarranties: 'Dhamana zilizoisha',
    expiredWarrantiesHint: 'dhamana imeisha — inaweza kuhifadhiwa',
    archiveReceipt: 'Hifadhi',
    restoreReceipt: 'Rudisha',
    showArchived: 'Onyesha zilizohifadhiwa',
    showActive: 'Onyesha zinazotumika',
    contactType: 'Aina',
    winga: 'Winga',
    walkInCustomer: 'Mteja',
    noWarranty: 'Hakuna dhamana',

    // Products
    products: 'Bidhaa',
    searchProducts: 'Tafuta bidhaa...',
    noProducts: 'Hakuna Bidhaa',
    addFirstProduct: 'Ongeza bidhaa yako ya kwanza kuanza',
    editProduct: 'Hariri Bidhaa',
    productName: 'Jina la Bidhaa',
    enterProductName: 'Ingiza jina la bidhaa',
    brand: 'Chapa',
    enterBrand: 'Ingiza chapa',
    category: 'Aina',
    enterCategory: 'Ingiza aina',
    buyingPrice: 'Bei ya Ununuzi',
    sellingPrice: 'Bei ya Mauzo',
    pieces: 'Vipande',
    lowStockAlert: 'Arifa ya Stock Kidogo',
    calculations: 'Mahesabu',
    profitPerUnit: 'Faida kwa Kipande',
    profitMargin: 'Uwiano wa Faida',
    totalCost: 'Gharama Jumla',
    profit: 'Faida',
    totalValue: 'Thamani Jumla',
    lowStockWarning: 'Onyo la stock kidogo',
    threshold: 'Kiwango',

    // Sales
    pointOfSale: 'Mahali pa Mauzo',
    cart: 'Kikapu',
    addToCart: 'Weka Kikabuni',
    removeFromCart: 'Ondoa Kikabuni',
    clearCart: 'Safisha Kikapu',
    checkout: 'Maliza Ununuzi',
    total: 'Jumla',
    subtotal: 'Jumla Ndogo',
    cash: 'Pesa Taslimu',
    change: 'Chenji',
    completeSale: 'Maliza Mauzo',

    // Customers
    customers: 'Wateja',
    searchCustomers: 'Tafuta wateja...',
    noCustomers: 'Hakuna Wateja',
    addFirstCustomer: 'Ongeza mteja wako wa kwanza kuanza',
    editCustomer: 'Hariri Mteja',
    customerName: 'Jina la Mteja',
    enterCustomerName: 'Ingiza jina la mteja',
    phoneNumber: 'Nambari ya Simu',
    enterPhoneNumber: 'Ingiza nambari ya simu',
    email: 'Barua Pepe',
    enterEmail: 'Ingiza anwani ya barua pepe',
    address: 'Anwani',
    enterAddress: 'Ingiza anwani',
    loyaltyPoints: 'Alama za Uongozi',
    loanBalance: 'Salio la Mkopo',
    payLoan: 'Lipa Mkopo',
    addLoan: 'Ongeza Mkopo',
    loanHistory: 'Historia ya Mikopo',

    // Reports
    reports: 'Ripoti na Takwimu',
    financialSummary: 'Muhtasari wa Fedha',
    lossInformation: 'Taarifa ya Hasara',
    currentLoss: 'Hasara ya Sasa',
    currentProfit: 'Faida ya Sasa',
    revenue: 'Mapato',
    cost: 'Gharama',
    keyMetrics: 'Vipimo Muhimu',
    totalSales: 'Jumla ya Mauzo',
    inventoryValue: 'Thamani ya Hesabu',
    activeCustomers: 'Wateja Hai',
    pendingLoansReport: 'Mikopo Inayosubiri',
    lowStockAlertReport: 'Arifa ya Stock Kidogo',
    productPerformance: 'Utendaji wa Bidhaa',
    customerInsights: 'Maarifa ya Wateja',
    totalLoyaltyPoints: 'Jumla ya Alama za Uaminifu',
    customersWithLoans: 'Wateja wenye Mikopo',
    averageLoan: 'Wastani wa Mkopo',
    today: 'Leo',
    week: 'Wiki',
    month: 'Mwezi',
    remaining: 'zilizobaki',
    units: 'vipande',
    items: 'bidhaa',

    // Common
    save: 'Hifadhi',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    add: 'Ongeza',
    search: 'Tafuta',
    filter: 'Chuja',
    sort: 'Panga',
    error: 'Kosa',
    success: 'Mafanikio',
    warning: 'Onyo',
    confirmDelete: 'Thibitisha Kufuta',
    confirmDeleteProduct: 'Una uhakika unataka kufuta bidhaa hii?',
    confirmDeleteCustomer: 'Una uhakika unataka kufuta mteja huyu?',
    fillAllFields: 'Tafadhali jaza vuga vyote vinavyohitajika',
    ok: 'Sawa',
    home: 'Mwanzo', pos: 'Mauzo', receipts: 'Risiti', workspace: 'Eneo la biashara',
    price: 'Bei', stock: 'Stoo', actions: 'Vitendo', totalLoans: 'Jumla ya Mikopo', totalPoints: 'Jumla ya Pointi',
    selectCustomer: 'Chagua Mteja', newProduct: 'Bidhaa mpya', saveAndAdd: 'Hifadhi na ongeza',
    orderSummary: 'Muhtasari wa Oda', payment: 'Malipo', customerNameOptional: 'Jina la mteja (si lazima)',
    enterCustomerReceipt: 'Ingiza jina la mteja kwa ajili ya risiti', selectCustomerTitle: 'Chagua Mteja',
    done: 'Imekamilika', applyDiscount: 'Weka Punguzo', apply: 'Weka', discountPercentage: 'Asilimia ya Punguzo (%)',
    saleReceipt: 'Risiti ya Mauzo', receiptDetails: 'Maelezo ya Risiti', receiptsHistory: 'Historia ya risiti',
    searchReceipts: 'Tafuta kwa namba, tarehe, au kiasi...', noReceipts: 'Hakuna risiti zilizopatikana',
    adjustSearch: 'Jaribu kubadilisha utafutaji', receiptsAfterSales: 'Risiti zitaonekana hapa baada ya mauzo',
    customerInformation: 'Taarifa za Mteja', cashSaleNoCustomer: 'Hakuna Mteja (Mauzo ya Taslimu)',
    itemsPurchased: 'Bidhaa Zilizonunuliwa', cashReceived: 'Fedha Iliyopokelewa',
    signature: 'Sahihi', notes: 'Maelezo ya Ziada', enterSignature: 'Ingiza sahihi',
    enterNotes: 'Ongeza maelezo ya ziada', productOutOfStock: 'Bidhaa imeisha stoo',
    notEnoughStock: 'Idadi iliyopo stoo haitoshi', cartEmpty: 'Kikapu hakina bidhaa', insufficientCash: 'Fedha iliyopokelewa haitoshi',
    loan: 'Mkopo', loanManagement: 'Usimamizi wa Mkopo', addLoanAmount: 'Kiasi cha Kuongeza Mkopo', paymentAmount: 'Kiasi cha Malipo',
    newBalanceCalculation: 'Hesabu ya Salio Jipya', createAccount: 'Fungua Akaunti', welcomeBack: 'Karibu Tena',
    signIn: 'Ingia', signUp: 'Jisajili', password: 'Nenosiri', confirmPassword: 'Thibitisha Nenosiri',
    fullName: 'Jina Kamili', shopName: 'Jina la Duka', username: 'Jina la Mtumiaji', phone: 'Simu',
    resetPassword: 'Weka Upya Nenosiri', updatePassword: 'Badilisha nenosiri',
    expenses: 'Matumizi', monthlyExpenses: 'Mwezi huu', addExpense: 'Ongeza Matumizi', amount: 'Kiasi',
    description: 'Maelezo', noDescription: 'Hakuna maelezo', noExpenses: 'Hakuna matumizi yaliyorekodiwa',
    validExpense: 'Ingiza aina na kiasi kikubwa kuliko sifuri', expenseSaveFailed: 'Matumizi hayakuweza kuhifadhiwa',
    netProfit: 'Faida Halisi', operatingExpenses: 'Matumizi ya Uendeshaji', inventoryMovements: 'Mabadiliko ya Stoo',
    more: 'Zaidi', inventory: 'Stoo', businessTools: 'Zana na kumbukumbu za biashara',
    customerManagement: 'Akaunti, uaminifu na mikopo ya wateja', expenseManagement: 'Rekodi na kagua gharama za uendeshaji',
    shareReceipt: 'Shiriki / PDF',
    allowPopups: 'Ruhusu madirisha ibukizi ili kufungua risiti ya kuchapisha',

    // Njia za malipo
    paymentMethod: 'Njia ya Malipo',
    cashPayment: 'Taslimu',
    mpesa: 'M-Pesa',
    tigopesa: 'Mixx by Yas',
    airtelmoney: 'Airtel Money',
    halopesa: 'HaloPesa',
    azampesa: 'Azam Pesa',
    bankTransfer: 'Benki',
    splitPayment: 'Malipo Mchanganyiko',
    reference: 'Kumbukumbu',
    transactionRef: 'Namba ya muamala',
    enterReference: 'Weka namba ya muamala',

    // Namba za IMEI
    serialNumbers: 'Namba za IMEI',
    addImei: 'Ongeza IMEI',
    imeiList: 'IMEI Zilizosajiliwa',
    searchByImei: 'Tafuta kwa IMEI, jina au chapa',
    imeiNotFound: 'Hakuna bidhaa yenye IMEI hiyo',
    imeiAlreadyExists: 'IMEI hiyo tayari imesajiliwa',
    imeiInvalid: 'IMEI lazima iwe na tarakimu 15',
    selectUnit: 'Chagua kifaa',
    unitStatus: 'Hali',
    unitInStock: 'Ipo stoo',
    unitSold: 'Imeuzwa',
    unitReturned: 'Imerudishwa',
    unitFaulty: 'Ina hitilafu',
    unitsRequired: 'Sajili IMEI moja kwa kila simu iliyopo stoo',
    imeiLookup: 'Tafuta IMEI',
    soldOn: 'Iliuzwa tarehe',
    soldTo: 'Iliuzwa kwa',
    warranty: 'Dhamana',
    warrantyValid: 'Ina dhamana',
    warrantyExpired: 'Dhamana imeisha',

    // Hasara na marejesho
    recordLoss: 'Andika Hasara',
    lossReason: 'Sababu',
    damaged: 'Imeharibika',
    stolen: 'Imeibiwa',
    defective: 'Ina kasoro',
    lostItem: 'Imepotea',
    returnSale: 'Rejesha / Rudisha Fedha',
    processReturn: 'Fanya Marejesho',
    returnReason: 'Sababu ya kurejesha',
    refundAmount: 'Kiasi cha kurudisha',
    returnRecorded: 'Marejesho yamehifadhiwa na stoo imerekebishwa',

    // Mwonekano na mfumo
    appearance: 'Mwonekano',
    lightMode: 'Mwanga',
    darkMode: 'Giza',
    systemMode: 'Mfumo',
    settings: 'Mipangilio',
    language: 'Lugha',
    offline: 'Hakuna Mtandao',
    online: 'Mtandaoni',
    offlineNotice: 'Hauna mtandao. Mauzo yanahifadhiwa kwenye kifaa na yatatumwa yenyewe.',
    pendingSync: 'yanasubiri kutumwa',
    syncNow: 'Tuma sasa',
    syncing: 'Inatuma',
    synced: 'Kila kitu kimetumwa',
    retry: 'Jaribu tena',
    close: 'Funga',
    all: 'Zote',
    clear: 'Futa',

    // Makosa ya kujisajili
    usernameTaken: 'Jina hilo la mtumiaji limeshatumika. Chagua lingine.',
    usernameChecking: 'Inaangalia upatikanaji…',
    usernameAvailable: 'Jina la mtumiaji linapatikana',
    emailRateLimited: 'Barua pepe nyingi za uthibitisho zimetumwa. Subiri takribani saa moja kisha ujaribu tena.',
    emailNotConfirmed: 'Barua pepe yako haijathibitishwa. Angalia kikasha chako, au tuma tena barua ya uthibitisho hapa chini.',
    invalidCredentials: 'Barua pepe au nenosiri si sahihi. Tumia barua pepe uliyojisajili nayo.',
    signupSuccess: 'Akaunti imetengenezwa. Angalia barua pepe yako kuthibitisha kabla ya kuingia.',
    verificationSent: 'Barua ya uthibitisho imetumwa. Angalia kikasha chako na folda ya taka.',
    passwordTooShort: 'Nenosiri lazima liwe na herufi 6 au zaidi',
    passwordsDoNotMatch: 'Manenosiri hayafanani',
    enterEmailFirst: 'Weka barua pepe yako kwanza.',
    unexpectedError: 'Kuna hitilafu imetokea. Tafadhali jaribu tena.',
    passwordUpdated: 'Nenosiri lako limebadilishwa.',
    resetLinkExpired: 'Kiungo hiki cha kubadili nenosiri kimeisha muda au kimeshatumika. Omba kingine.',

    // Zilizokuwa hazipo: zilionekana kama majina ya funguo skrini.
    accessories: 'Vifaa',
    reportsShort: 'Ripoti',
    phones: 'Simu',
    enterIMEI: 'Weka IMEI ya tarakimu 15',
    product: 'Bidhaa',
    quantity: 'Idadi',
    loss: 'Hasara',
    piecesSold: 'zimeuzwa',
    discountSummary: 'Punguzo',
    totalDiscountsGiven: 'Jumla ya Punguzo',
    averageDiscount: 'Wastani wa Punguzo',
  },
};

interface LanguageContextType {
  language: 'en' | 'sw';
  setLanguage: (lang: 'en' | 'sw') => void;
  t: (key: string) => string;
  toggleLanguage: () => void;
  isSwahili: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Swahili is the working language of most Tanzanian phone counters, so it is
  // the default rather than an opt-in.
  const [language, setLanguageState] = useState<'en' | 'sw'>('sw');

  useEffect(() => {
    let active = true;
    storage.get(STORAGE_KEYS.language).then(saved => {
      if (active && (saved === 'en' || saved === 'sw')) setLanguageState(saved);
    });
    return () => {
      active = false;
    };
  }, []);

  const setLanguage = (next: 'en' | 'sw') => {
    setLanguageState(next);
    void storage.set(STORAGE_KEYS.language, next);
  };

  const value = useMemo(() => {
    // Fall back to English before the raw key so a missing Swahili string shows
    // real words instead of `lowStockAlert` on the shop floor.
    const t = (key: string): string =>
      translations[language][key] || translations.en[key] || key;

    return {
      language,
      setLanguage,
      t,
      toggleLanguage: () => setLanguage(language === 'sw' ? 'en' : 'sw'),
      isSwahili: language === 'sw',
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
